console.log('├── 여기는 이어지는 곳');
console.log('├── 여기는 이어지는 곳');
console.log('├── 여기는 이어지는 곳');
console.log('├── 여기는 이어지는 곳');
console.log('│  ├── 여기는 파일명');
console.log('│  └── 여기는 파일명');
console.log('├── 여기는 이어지는 곳');
console.log('├── 여기는 이어지는 곳');
console.log('├── 여기는 이어지는 곳');
console.log('└── 여기는 파일명');